version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-version:
      nodejs: 14
    commands:
        - echo Installing soirce NPM dependencies...
        - npm install -y npm@latest
        - npm install -g @angular/cli
        - rm package-lock.json
  build:
    commands:
        - echo Build started
        - ng build --prod
  post_build:
    commands:
        - echo Updating files in the S3 bucket...
        - aws s3 sync dist/krm-web/ s3://krm-poc-bucket --delete
